#!/usr/bin/env bash


LOCAL_FILE_PATH="dummy"
TOPIC_NAME="dummy"
DELAY_IN_MS="dummy"


COUNT_STREAM_APP_ID="dummy"
COUNT_STREAM_TOPIC_DEP="dummy"
COUNT_STREAM_STORE_NAME="dummy"
COUNT_STREAM_TOPIC_EMPLOYEE="dummy"
COUNT_STREAM_TOPIC_EMPLOYEE_COUNT="dummy"
COUNT_STREAM_TOPIC_DEP_COUNT="dummy"